map ={ "height":10,
 "layers":[
        {
         "data":[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 2, 0, 0, 0, 0, 5, 4, 4, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 4, 4, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 1, 1, 1, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 1, 1, 1, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 1, 1, 1, 1, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 1, 1, 1, 1, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 13, 12, 12, 14, 4, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 1, 1, 12, 12, 1, 1, 1, 12, 12, 12, 1, 4, 2, 0, 0, 0, 0, 0, 0, 0, 3, 1, 1, 12, 12, 4, 4, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 20, 16, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 4, 4, 4, 7, 1, 1, 1, 1, 1, 1, 1, 1, 12, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 1, 1, 1, 1, 1, 1, 1, 1, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 1, 1, 12, 12, 4, 4, 2, 6, 0, 0, 0, 0, 3, 13, 12, 12, 14, 4, 4, 4, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 20, 1, 1, 1, 21, 0, 0, 0, 0, 0, 0, 0, 0, 3, 1, 1, 1, 1, 1, 7, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 12, 12, 12, 4, 4, 4, 4, 13, 12, 12, 14, 1, 1, 1, 1, 1, 1, 1, 1, 1, 6, 0, 0, 3, 1, 1, 12, 12, 1, 1, 1, 1, 1, 1, 1, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 1, 1, 1, 1, 1, 1, 7, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 12, 12, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         "height":10,
         "name":"Tile Layer 1",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":100,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "height":0,
         "name":"Object Layer 1",
         "objects":[
                {
                 "height":30,
                 "id":1,
                 "name":"player",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":27.3333,
                 "x":2.66667000000001,
                 "y":128
                }, 
                {
                 "height":0.666667,
                 "id":2,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":5.33333,
                 "y":260.667
                }, 
                {
                 "gid":31,
                 "height":32,
                 "id":6,
                 "name":"",
                 "rotation":0,
                 "type":"diamond",
                 "visible":true,
                 "width":32,
                 "x":992.333,
                 "y":255.333
                }, 
                {
                 "gid":31,
                 "height":37,
                 "id":7,
                 "name":"",
                 "rotation":0,
                 "type":"diamond",
                 "visible":true,
                 "width":32,
                 "x":192,
                 "y":161
                }, 
                {
                 "gid":41,
                 "height":32,
                 "id":8,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":353,
                 "y":192
                }, 
                {
                 "gid":31,
                 "height":37,
                 "id":10,
                 "name":"",
                 "rotation":0,
                 "type":"diamond",
                 "visible":true,
                 "width":32,
                 "x":414,
                 "y":194.5
                }, 
                {
                 "gid":31,
                 "height":37,
                 "id":11,
                 "name":"",
                 "rotation":0,
                 "type":"diamond",
                 "visible":true,
                 "width":32,
                 "x":607,
                 "y":224.5
                }, 
                {
                 "gid":43,
                 "height":32,
                 "id":12,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":96,
                 "y":159
                }, 
                {
                 "gid":50,
                 "height":32,
                 "id":17,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":1,
                 "y":162
                }, 
                {
                 "gid":44,
                 "height":32,
                 "id":18,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":284,
                 "y":193
                }, 
                {
                 "gid":38,
                 "height":32,
                 "id":19,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":80,
                 "y":63
                }, 
                {
                 "gid":28,
                 "height":32,
                 "id":21,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":287,
                 "y":66
                }, 
                {
                 "gid":45,
                 "height":32,
                 "id":22,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":415,
                 "y":63
                }, 
                {
                 "gid":45,
                 "height":32,
                 "id":23,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":447,
                 "y":63
                }, 
                {
                 "gid":28,
                 "height":32,
                 "id":24,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":322,
                 "y":64
                }, 
                {
                 "gid":23,
                 "height":32,
                 "id":25,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":478,
                 "y":96
                }, 
                {
                 "gid":23,
                 "height":32,
                 "id":26,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":384,
                 "y":97
                }, 
                {
                 "gid":35,
                 "height":32,
                 "id":27,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":254,
                 "y":192
                }, 
                {
                 "gid":35,
                 "height":32,
                 "id":28,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":156,
                 "y":159
                }, 
                {
                 "gid":41,
                 "height":32,
                 "id":29,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":768,
                 "y":193
                }, 
                {
                 "gid":46,
                 "height":32,
                 "id":30,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":1058,
                 "y":94
                }, 
                {
                 "gid":41,
                 "height":32,
                 "id":31,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":1055,
                 "y":258
                }, 
                {
                 "gid":41,
                 "height":32,
                 "id":34,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":1411,
                 "y":256
                }, 
                {
                 "gid":41,
                 "height":32,
                 "id":35,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":1565,
                 "y":193
                }, 
                {
                 "gid":41,
                 "height":32,
                 "id":36,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":1666,
                 "y":223
                }, 
                {
                 "gid":31,
                 "height":37,
                 "id":37,
                 "name":"",
                 "rotation":0,
                 "type":"diamond",
                 "visible":true,
                 "width":32,
                 "x":863,
                 "y":195.5
                }, 
                {
                 "gid":31,
                 "height":37,
                 "id":38,
                 "name":"",
                 "rotation":0,
                 "type":"diamond",
                 "visible":true,
                 "width":32,
                 "x":1185,
                 "y":258.5
                }, 
                {
                 "gid":31,
                 "height":37,
                 "id":39,
                 "name":"",
                 "rotation":0,
                 "type":"diamond",
                 "visible":true,
                 "width":32,
                 "x":1629,
                 "y":225.5
                }, 
                {
                 "gid":31,
                 "height":37,
                 "id":40,
                 "name":"",
                 "rotation":0,
                 "type":"diamond",
                 "visible":true,
                 "width":32,
                 "x":1727,
                 "y":225.5
                }, 
                {
                 "gid":25,
                 "height":32,
                 "id":41,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":1856.5,
                 "y":127
                }, 
                {
                 "gid":24,
                 "height":32,
                 "id":42,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":1889.5,
                 "y":127
                }, 
                {
                 "gid":43,
                 "height":32,
                 "id":43,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":1873,
                 "y":64
                }, 
                {
                 "gid":48,
                 "height":32,
                 "id":44,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":31,
                 "x":2880,
                 "y":130
                }, 
                {
                 "gid":48,
                 "height":32,
                 "id":45,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":2912,
                 "y":129
                }, 
                {
                 "gid":40,
                 "height":32,
                 "id":46,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":2433,
                 "y":67
                }, 
                {
                 "gid":44,
                 "height":32,
                 "id":47,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":2428,
                 "y":255
                }, 
                {
                 "gid":45,
                 "height":32,
                 "id":48,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":2753,
                 "y":257
                }, 
                {
                 "gid":45,
                 "height":32,
                 "id":49,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":2786,
                 "y":256
                }, 
                {
                 "gid":45,
                 "height":32,
                 "id":50,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":2848,
                 "y":257
                }, 
                {
                 "gid":45,
                 "height":32,
                 "id":51,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":2881,
                 "y":257
                }, 
                {
                 "gid":45,
                 "height":32,
                 "id":52,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":2944,
                 "y":257
                }, 
                {
                 "gid":31,
                 "height":37,
                 "id":53,
                 "name":"",
                 "rotation":0,
                 "type":"diamond",
                 "visible":true,
                 "width":32,
                 "x":2015,
                 "y":225.5
                }, 
                {
                 "gid":31,
                 "height":37,
                 "id":54,
                 "name":"",
                 "rotation":0,
                 "type":"diamond",
                 "visible":true,
                 "width":32,
                 "x":2274,
                 "y":259.5
                }, 
                {
                 "gid":31,
                 "height":37,
                 "id":55,
                 "name":"",
                 "rotation":0,
                 "type":"diamond",
                 "visible":true,
                 "width":32,
                 "x":2496,
                 "y":257.5
                }, 
                {
                 "gid":31,
                 "height":37,
                 "id":56,
                 "name":"",
                 "rotation":0,
                 "type":"diamond",
                 "visible":true,
                 "width":32,
                 "x":2687,
                 "y":192.5
                }, 
                {
                 "gid":31,
                 "height":37,
                 "id":57,
                 "name":"",
                 "rotation":0,
                 "type":"diamond",
                 "visible":true,
                 "width":32,
                 "x":3102,
                 "y":193.5
                }, 
                {
                 "gid":32,
                 "height":32,
                 "id":58,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":3169,
                 "y":191
                }, 
                {
                 "gid":41,
                 "height":32,
                 "id":59,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":1856,
                 "y":288
                }, 
                {
                 "gid":41,
                 "height":32,
                 "id":60,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":2145,
                 "y":224
                }, 
                {
                 "gid":41,
                 "height":32,
                 "id":61,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":2338,
                 "y":257
                }, 
                {
                 "gid":41,
                 "height":32,
                 "id":62,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":2914,
                 "y":259
                }, 
                {
                 "gid":41,
                 "height":32,
                 "id":63,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":2654,
                 "y":190
                }, 
                {
                 "gid":36,
                 "height":32,
                 "id":65,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":1469,
                 "y":257
                }, 
                {
                 "gid":35,
                 "height":32,
                 "id":66,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":1219,
                 "y":252
                }, 
                {
                 "gid":39,
                 "height":32,
                 "id":67,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":1153,
                 "y":162
                }, 
                {
                 "gid":49,
                 "height":32,
                 "id":68,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":1120,
                 "y":256
                }, 
                {
                 "gid":49,
                 "height":32,
                 "id":69,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":1538,
                 "y":191
                }, 
                {
                 "gid":49,
                 "height":32,
                 "id":70,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":706,
                 "y":157
                }, 
                {
                 "gid":27,
                 "height":32,
                 "id":71,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":511,
                 "y":224
                }, 
                {
                 "gid":27,
                 "height":32,
                 "id":72,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":545,
                 "y":223
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "width":0,
         "x":0,
         "y":0
        }],
 "nextobjectid":73,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tileheight":32,
 "tilesets":[
        {
         "columns":0,
         "firstgid":1,
         "margin":0,
         "name":"a",
         "spacing":0,
         "tilecount":22,
         "tileheight":32,
         "tiles":
            {
             "0":
                {
                 "image":"res\/png\/tiles\/01.png"
                },
             "1":
                {
                 "image":"res\/png\/tiles\/02.png"
                },
             "10":
                {
                 "image":"res\/png\/tiles\/11.png"
                },
             "11":
                {
                 "image":"res\/png\/tiles\/12.png"
                },
             "12":
                {
                 "image":"res\/png\/tiles\/13.png"
                },
             "13":
                {
                 "image":"res\/png\/tiles\/14.png"
                },
             "14":
                {
                 "image":"res\/png\/tiles\/15.png"
                },
             "15":
                {
                 "image":"res\/png\/tiles\/16.png"
                },
             "16":
                {
                 "image":"res\/png\/tiles\/17.png"
                },
             "17":
                {
                 "image":"res\/png\/tiles\/18.png"
                },
             "18":
                {
                 "image":"res\/png\/tiles\/19.png"
                },
             "19":
                {
                 "image":"res\/png\/tiles\/20.png"
                },
             "2":
                {
                 "image":"res\/png\/tiles\/03.png"
                },
             "20":
                {
                 "image":"res\/png\/tiles\/21.png"
                },
             "21":
                {
                 "image":"res\/png\/tiles\/22.png"
                },
             "3":
                {
                 "image":"res\/png\/tiles\/04.png"
                },
             "4":
                {
                 "image":"res\/png\/tiles\/05.png"
                },
             "5":
                {
                 "image":"res\/png\/tiles\/06.png"
                },
             "6":
                {
                 "image":"res\/png\/tiles\/07.png"
                },
             "7":
                {
                 "image":"res\/png\/tiles\/08.png"
                },
             "8":
                {
                 "image":"res\/png\/tiles\/09.png"
                },
             "9":
                {
                 "image":"res\/png\/tiles\/10.png"
                }
            },
         "tilewidth":32
        }, 
        {
         "columns":0,
         "firstgid":23,
         "margin":0,
         "name":"b",
         "spacing":0,
         "tilecount":28,
         "tileheight":32,
         "tiles":
            {
             "0":
                {
                 "image":"res\/png\/elements\/32x32\/blade.png"
                },
             "1":
                {
                 "image":"res\/png\/elements\/32x32\/box1.png"
                },
             "10":
                {
                 "image":"res\/png\/elements\/32x32\/flower1.png"
                },
             "11":
                {
                 "image":"res\/png\/elements\/32x32\/flower2.png"
                },
             "12":
                {
                 "image":"res\/png\/elements\/32x32\/flower3.png"
                },
             "13":
                {
                 "image":"res\/png\/elements\/32x32\/flower4.png"
                },
             "14":
                {
                 "image":"res\/png\/elements\/32x32\/flower5.png"
                },
             "15":
                {
                 "image":"res\/png\/elements\/32x32\/heart.png"
                },
             "16":
                {
                 "image":"res\/png\/elements\/32x32\/key.png"
                },
             "17":
                {
                 "image":"res\/png\/elements\/32x32\/lever.png"
                },
             "18":
                {
                 "image":"res\/png\/elements\/32x32\/plate1.png"
                },
             "19":
                {
                 "image":"res\/png\/elements\/32x32\/plate2.png"
                },
             "2":
                {
                 "image":"res\/png\/elements\/32x32\/box2.png"
                },
             "20":
                {
                 "image":"res\/png\/elements\/32x32\/pointer.png"
                },
             "21":
                {
                 "image":"res\/png\/elements\/32x32\/scarecrow.png"
                },
             "22":
                {
                 "image":"res\/png\/elements\/32x32\/stairs.png"
                },
             "23":
                {
                 "image":"res\/png\/elements\/32x32\/star.png"
                },
             "24":
                {
                 "image":"res\/png\/elements\/32x32\/thorns1.png"
                },
             "25":
                {
                 "image":"res\/png\/elements\/32x32\/thorns2.png"
                },
             "26":
                {
                 "image":"res\/png\/elements\/32x32\/tree1.png"
                },
             "27":
                {
                 "image":"res\/png\/elements\/32x32\/tree2.png"
                },
             "3":
                {
                 "image":"res\/png\/elements\/32x32\/bush1.png"
                },
             "4":
                {
                 "image":"res\/png\/elements\/32x32\/bush2.png"
                },
             "5":
                {
                 "image":"res\/png\/elements\/32x32\/button.png"
                },
             "6":
                {
                 "image":"res\/png\/elements\/32x32\/cell.png"
                },
             "7":
                {
                 "image":"res\/png\/elements\/32x32\/coin.png"
                },
             "8":
                {
                 "image":"res\/png\/elements\/32x32\/crystal.png"
                },
             "9":
                {
                 "image":"res\/png\/elements\/32x32\/door.png"
                }
            },
         "tilewidth":32
        }],
 "tilewidth":32,
 "version":1,
 "width":100
}