map = { "height":10,
 "layers":[
        {
         "data":[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 4, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 1, 1, 1, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 1, 1, 1, 1, 2, 0, 3, 4, 4, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 4, 13, 12, 12, 12, 14, 2, 4, 4, 6, 0, 44, 0, 9, 4, 0, 0, 0, 9, 1, 1, 1, 13, 12, 14, 1, 8, 1, 1, 1, 13, 12, 14, 1, 1, 1, 4, 4, 1, 1, 1, 1, 1, 12, 1, 1, 8],
         "height":10,
         "name":"Tile Layer 1",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":20,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "height":10,
         "name":"Object Layer 1",
         "objects":[
                {
                 "height":32,
                 "id":6,
                 "name":"player",
                 "rotation":0,
                 "type":"player",
                 "visible":true,
                 "width":32,
                 "x":0,
                 "y":225
                }, 
                {
                 "gid":47,
                 "height":32,
                 "id":8,
                 "name":"",
                 "rotation":0,
                 "type":"spikes",
                 "visible":true,
                 "width":32,
                 "x":256,
                 "y":289
                }, 
                {
                 "gid":31,
                 "height":32,
                 "id":10,
                 "name":"",
                 "rotation":0,
                 "type":"diamond",
                 "visible":true,
                 "width":32,
                 "x":289,
                 "y":286
                }, 
                {
                 "gid":38,
                 "height":32,
                 "id":13,
                 "name":"",
                 "rotation":0,
                 "type":"heart",
                 "visible":true,
                 "width":32,
                 "x":351,
                 "y":127
                }, 
                {
                 "gid":30,
                 "height":32,
                 "id":16,
                 "name":"",
                 "rotation":0,
                 "type":"coin",
                 "visible":true,
                 "width":32,
                 "x":511,
                 "y":223
                }, 
                {
                 "gid":32,
                 "height":32,
                 "id":17,
                 "name":"",
                 "rotation":0,
                 "type":"exit",
                 "visible":true,
                 "width":32,
                 "x":607,
                 "y":225
                }, 
                {
                 "gid":30,
                 "height":32,
                 "id":22,
                 "name":"",
                 "rotation":0,
                 "type":"coin",
                 "visible":true,
                 "width":32,
                 "x":96,
                 "y":65
                }, 
                {
                 "gid":47,
                 "height":32,
                 "id":23,
                 "name":"",
                 "rotation":0,
                 "type":"spikes",
                 "visible":true,
                 "width":32,
                 "x":95,
                 "y":97
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "width":20,
         "x":0,
         "y":0
        }],
 "nextobjectid":24,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tileheight":32,
 "tilesets":[
        {
         "columns":0,
         "firstgid":1,
         "margin":0,
         "name":"1",
         "spacing":0,
         "tilecount":22,
         "tileheight":32,
         "tiles":
            {
             "0":
                {
                 "image":"res\/png\/tiles\/01.png"
                },
             "1":
                {
                 "image":"res\/png\/tiles\/02.png"
                },
             "10":
                {
                 "image":"res\/png\/tiles\/11.png"
                },
             "11":
                {
                 "image":"res\/png\/tiles\/12.png"
                },
             "12":
                {
                 "image":"res\/png\/tiles\/13.png"
                },
             "13":
                {
                 "image":"res\/png\/tiles\/14.png"
                },
             "14":
                {
                 "image":"res\/png\/tiles\/15.png"
                },
             "15":
                {
                 "image":"res\/png\/tiles\/16.png"
                },
             "16":
                {
                 "image":"res\/png\/tiles\/17.png"
                },
             "17":
                {
                 "image":"res\/png\/tiles\/18.png"
                },
             "18":
                {
                 "image":"res\/png\/tiles\/19.png"
                },
             "19":
                {
                 "image":"res\/png\/tiles\/20.png"
                },
             "2":
                {
                 "image":"res\/png\/tiles\/03.png"
                },
             "20":
                {
                 "image":"res\/png\/tiles\/21.png"
                },
             "21":
                {
                 "image":"res\/png\/tiles\/22.png"
                },
             "3":
                {
                 "image":"res\/png\/tiles\/04.png"
                },
             "4":
                {
                 "image":"res\/png\/tiles\/05.png"
                },
             "5":
                {
                 "image":"res\/png\/tiles\/06.png"
                },
             "6":
                {
                 "image":"res\/png\/tiles\/07.png"
                },
             "7":
                {
                 "image":"res\/png\/tiles\/08.png"
                },
             "8":
                {
                 "image":"res\/png\/tiles\/09.png"
                },
             "9":
                {
                 "image":"res\/png\/tiles\/10.png"
                }
            },
         "tilewidth":32
        }, 
        {
         "columns":0,
         "firstgid":23,
         "margin":0,
         "name":"elements",
         "spacing":0,
         "tilecount":28,
         "tileheight":32,
         "tiles":
            {
             "0":
                {
                 "image":"res\/png\/elements\/32x32\/blade.png"
                },
             "1":
                {
                 "image":"res\/png\/elements\/32x32\/box1.png"
                },
             "10":
                {
                 "image":"res\/png\/elements\/32x32\/flower1.png"
                },
             "11":
                {
                 "image":"res\/png\/elements\/32x32\/flower2.png"
                },
             "12":
                {
                 "image":"res\/png\/elements\/32x32\/flower3.png"
                },
             "13":
                {
                 "image":"res\/png\/elements\/32x32\/flower4.png"
                },
             "14":
                {
                 "image":"res\/png\/elements\/32x32\/flower5.png"
                },
             "15":
                {
                 "image":"res\/png\/elements\/32x32\/heart.png"
                },
             "16":
                {
                 "image":"res\/png\/elements\/32x32\/key.png"
                },
             "17":
                {
                 "image":"res\/png\/elements\/32x32\/lever.png"
                },
             "18":
                {
                 "image":"res\/png\/elements\/32x32\/plate1.png"
                },
             "19":
                {
                 "image":"res\/png\/elements\/32x32\/plate2.png"
                },
             "2":
                {
                 "image":"res\/png\/elements\/32x32\/box2.png"
                },
             "20":
                {
                 "image":"res\/png\/elements\/32x32\/pointer.png"
                },
             "21":
                {
                 "image":"res\/png\/elements\/32x32\/scarecrow.png"
                },
             "22":
                {
                 "image":"res\/png\/elements\/32x32\/stairs.png"
                },
             "23":
                {
                 "image":"res\/png\/elements\/32x32\/star.png"
                },
             "24":
                {
                 "image":"res\/png\/elements\/32x32\/thorns1.png"
                },
             "25":
                {
                 "image":"res\/png\/elements\/32x32\/thorns2.png"
                },
             "26":
                {
                 "image":"res\/png\/elements\/32x32\/tree1.png"
                },
             "27":
                {
                 "image":"res\/png\/elements\/32x32\/tree2.png"
                },
             "3":
                {
                 "image":"res\/png\/elements\/32x32\/bush1.png"
                },
             "4":
                {
                 "image":"res\/png\/elements\/32x32\/bush2.png"
                },
             "5":
                {
                 "image":"res\/png\/elements\/32x32\/button.png"
                },
             "6":
                {
                 "image":"res\/png\/elements\/32x32\/cell.png"
                },
             "7":
                {
                 "image":"res\/png\/elements\/32x32\/coin.png"
                },
             "8":
                {
                 "image":"res\/png\/elements\/32x32\/crystal.png"
                },
             "9":
                {
                 "image":"res\/png\/elements\/32x32\/door.png"
                }
            },
         "tilewidth":32
        }],
 "tilewidth":32,
 "version":1,
 "width":20
}