map = { "height":10,
 "layers":[
        {
         "data":[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 16, 16, 16, 1, 1, 1, 1, 1, 1, 16, 16, 16, 0, 0, 0, 0, 0, 0, 0, 12, 12, 12, 12, 1, 1, 1, 1, 1, 1, 12, 12, 12, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
         "height":10,
         "name":"Tile Layer 1",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":20,
         "x":0,
         "y":0
        }],
 "nextobjectid":1,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tileheight":32,
 "tilesets":[
        {
         "columns":0,
         "firstgid":1,
         "margin":0,
         "name":"1",
         "spacing":0,
         "tilecount":22,
         "tileheight":32,
         "tiles":
            {
             "0":
                {
                 "image":"res\/png\/tiles\/01.png"
                },
             "1":
                {
                 "image":"res\/png\/tiles\/02.png"
                },
             "10":
                {
                 "image":"res\/png\/tiles\/11.png"
                },
             "11":
                {
                 "image":"res\/png\/tiles\/12.png"
                },
             "12":
                {
                 "image":"res\/png\/tiles\/13.png"
                },
             "13":
                {
                 "image":"res\/png\/tiles\/14.png"
                },
             "14":
                {
                 "image":"res\/png\/tiles\/15.png"
                },
             "15":
                {
                 "image":"res\/png\/tiles\/16.png"
                },
             "16":
                {
                 "image":"res\/png\/tiles\/17.png"
                },
             "17":
                {
                 "image":"res\/png\/tiles\/18.png"
                },
             "18":
                {
                 "image":"res\/png\/tiles\/19.png"
                },
             "19":
                {
                 "image":"res\/png\/tiles\/20.png"
                },
             "2":
                {
                 "image":"res\/png\/tiles\/03.png"
                },
             "20":
                {
                 "image":"res\/png\/tiles\/21.png"
                },
             "21":
                {
                 "image":"res\/png\/tiles\/22.png"
                },
             "3":
                {
                 "image":"res\/png\/tiles\/04.png"
                },
             "4":
                {
                 "image":"res\/png\/tiles\/05.png"
                },
             "5":
                {
                 "image":"res\/png\/tiles\/06.png"
                },
             "6":
                {
                 "image":"res\/png\/tiles\/07.png"
                },
             "7":
                {
                 "image":"res\/png\/tiles\/08.png"
                },
             "8":
                {
                 "image":"res\/png\/tiles\/09.png"
                },
             "9":
                {
                 "image":"res\/png\/tiles\/10.png"
                }
            },
         "tilewidth":32
        }],
 "tilewidth":32,
 "version":1,
 "width":20
}